// Generated by scripts/build_mobile_ui.py; edit the named source modules.
// mobile_inspector.js
const escapeHtml = (value) => String(value ?? "")
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;");

function shortTime(value) {
  const parsed = new Date(String(value || ""));
  if (Number.isNaN(parsed.getTime())) return String(value || "—");
  return new Intl.DateTimeFormat("zh-CN", {
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(parsed);
}

function score(item) {
  const value = Number(item.score);
  return Number.isFinite(value) ? value.toFixed(3) : "";
}

function memoryList(items, empty) {
  if (!items.length) {
    return `<p class="akasha-mobile-empty">${escapeHtml(empty)}</p>`;
  }
  return `
    <ol class="akasha-mobile-memories">
      ${items.map((item) => `
        <li>
          <div>
            <p>${escapeHtml(item.user_preview || item.user_text || "（空消息）")}</p>
            ${item.assistant_preview
              ? `<p class="akasha-mobile-assistant">${escapeHtml(item.assistant_preview)}</p>`
              : ""}
          </div>
          <span>${escapeHtml(shortTime(item.ts))}${score(item) ? ` · ${score(item)}` : ""}</span>
        </li>
      `).join("")}
    </ol>
  `;
}

function recallSection(title, items, lane, captureAvailable = true) {
  const count = captureAvailable ? items.length : "未记录";
  const empty = captureAvailable
    ? "本轮没有命中"
    : "这一轮没有保存模式补全读出";
  return `
    <details class="akasha-mobile-recall akasha-mobile-recall--${escapeHtml(lane)}" ${items.length ? "open" : ""}>
      <summary>
        <span>${escapeHtml(title)}</span>
        <b>${escapeHtml(count)}</b>
      </summary>
      ${memoryList(items, empty)}
    </details>
  `;
}

function renderRecent(items, total) {
  if (!items.length) {
    return `
      <section class="akasha-mobile-inspector">
        <header>
          <h2>Akasha Inspector</h2>
          <p>还没有可检查的检索记录。</p>
        </header>
      </section>
    `;
  }
  return `
    <section class="akasha-mobile-inspector">
      <header>
        <h2>Akasha Inspector</h2>
        <p>最近 30 轮，共 ${Number(total || 0)} 轮。点开一轮查看线索和模式补全。</p>
      </header>
      <ol class="akasha-mobile-turns">
        ${items.map((item) => `
          <li>
            <button type="button" data-akasha-query="${escapeHtml(item.query_id)}">
              <span>${escapeHtml(item.query_preview || item.query_text || "（空消息）")}</span>
              <small>${escapeHtml(shortTime(item.ts))} · ${Number(item.seed_count || 0)} seeds · ${item.recall_capture_available === false ? "未记录 recall" : `${Number(item.completion_count || 0)} recall`}</small>
            </button>
          </li>
        `).join("")}
      </ol>
    </section>
  `;
}

function renderDetail(item) {
  const left = Array.isArray(item.left) ? item.left : [];
  const right = Array.isArray(item.right) ? item.right : [];
  const toolLeft = Array.isArray(item.tool_left) ? item.tool_left : [];
  const toolRight = Array.isArray(item.tool_right) ? item.tool_right : [];
  const recallCaptured = item.recall_capture_available !== false;
  return `
    <section class="akasha-mobile-inspector">
      <button class="akasha-mobile-back" type="button" data-akasha-back>返回检索列表</button>
      <header>
        <p class="akasha-mobile-time">${escapeHtml(shortTime(item.ts))}</p>
        <h2>${escapeHtml(item.query_text || "（空消息）")}</h2>
        <dl class="akasha-mobile-metrics">
          <div><dt>线索</dt><dd>${Number(item.seed_count || 0)}</dd></div>
          <div><dt>补全</dt><dd>${Number(item.activation_count || 0)}</dd></div>
          <div><dt>左脑</dt><dd>${left.length}</dd></div>
          <div><dt>右脑</dt><dd>${recallCaptured ? right.length : "—"}</dd></div>
        </dl>
      </header>
      <div class="akasha-mobile-detail-lanes">
        ${recallSection("左脑 · 精确回忆", left, "precise")}
        ${recallSection("右脑 · 模式补全", right, "completion", recallCaptured)}
        ${toolLeft.length ? recallSection("工具回忆 · 精确回忆", toolLeft, "precise") : ""}
        ${toolRight.length ? recallSection("工具回忆 · 模式补全", toolRight, "completion") : ""}
      </div>
      <p class="akasha-mobile-convergence">${Number(item.pushes || 0)} 次扩散，残余 ${Number(item.residual_l1 || 0).toExponential(2)}</p>
    </section>
  `;
}

function mountRecall(host, context) {
  if (!context.capabilities?.queryTransports?.includes("https")) {
    host.innerHTML = '<p class="akasha-mobile-error">当前客户端版本不支持 Akasha 轻量数据通道，请更新后查看本轮记忆。</p>';
    return undefined;
  }
  host.innerHTML = '<p class="akasha-mobile-loading">正在读取本轮记忆…</p>';
  let active = true;
  let retryTimer;
  const activeMessage = context.messageId.startsWith("assistant:");
  const waitToRetry = () => new Promise((resolve) => {
    retryTimer = setTimeout(resolve, 250);
  });
  const load = async () => {
    while (active) {
      const result = await context.query(
        "recall.current",
        { message_id: context.messageId },
        { cache: activeMessage ? "none" : "immutable", transport: "https" },
      );
      if (!active) return;
      if (result.pending === true) {
        host.innerHTML = '<p class="akasha-mobile-loading">记忆生成中…</p>';
        await waitToRetry();
        continue;
      }
      const left = Array.isArray(result.left) ? result.left : [];
      const right = Array.isArray(result.right) ? result.right : [];
      const toolLeft = Array.isArray(result.tool_left) ? result.tool_left : [];
      const toolRight = Array.isArray(result.tool_right) ? result.tool_right : [];
      const recallCaptured = result.recall_capture_available !== false;
      host.innerHTML = `
        <div class="akasha-mobile-recall-group">
          ${recallSection("左脑 · 精确回忆", left, "precise")}
          ${recallSection("右脑 · 模式补全", right, "completion", recallCaptured)}
          ${toolLeft.length ? recallSection("工具回忆 · 精确回忆", toolLeft, "precise") : ""}
          ${toolRight.length ? recallSection("工具回忆 · 模式补全", toolRight, "completion") : ""}
        </div>
      `;
      return;
    }
  };
  load().catch((error) => {
    if (active) {
      host.innerHTML = `<p class="akasha-mobile-error">${escapeHtml(error.message || "记忆读取失败")}</p>`;
    }
  });
  return () => {
    active = false;
    if (retryTimer !== undefined) clearTimeout(retryTimer);
  };
}

function mountInspector(host, context) {
  let active = true;
  let recent = null;
  host.innerHTML = '<p class="akasha-mobile-loading">正在读取检索记录…</p>';

  const showRecent = () => {
    if (!recent) return;
    host.innerHTML = renderRecent(recent.items, recent.total);
    host.querySelectorAll("[data-akasha-query]").forEach((button) => {
      button.addEventListener("click", () => {
        const queryId = button.getAttribute("data-akasha-query");
        if (!queryId) return;
        host.innerHTML = '<p class="akasha-mobile-loading">正在读取这一轮…</p>';
        context.query("inspector.detail", { query_id: queryId }).then((item) => {
          if (!active) return;
          host.innerHTML = renderDetail(item);
          host.querySelector("[data-akasha-back]")?.addEventListener("click", showRecent);
        }).catch((error) => {
          if (active) {
            host.innerHTML = `<p class="akasha-mobile-error">${escapeHtml(error.message || "检索记录读取失败")}</p>`;
          }
        });
      });
    });
  };

  context.query("inspector.recent").then((result) => {
    if (!active) return;
    recent = {
      items: Array.isArray(result.items) ? result.items : [],
      total: Number(result.total || 0),
    };
    showRecent();
  }).catch((error) => {
    if (active) {
      host.innerHTML = `<p class="akasha-mobile-error">${escapeHtml(error.message || "检索记录读取失败")}</p>`;
    }
  });
  return () => { active = false; };
}


// mobile_graph_canvas.js
function drawMemoryGraph(host, data, options) {
  const width = 360;
  const height = options.aggregate ? Math.max(210, Math.ceil(data.nodes.length / 2) * 76 + 25) : 320;
  const points = new Map();
  data.nodes.forEach((node, index) => {
    if (options.aggregate) {
      points.set(node.id, { x: 95 + (index % 2) * 170, y: 45 + Math.floor(index / 2) * 76 });
    } else if (node.id === data.root_id) {
      points.set(node.id, { x: 180, y: 160 });
    } else {
      const angle = -Math.PI / 2 + (index - 1) * Math.PI * 2 / Math.max(1, data.nodes.length - 1);
      points.set(node.id, { x: 180 + Math.cos(angle) * 122, y: 160 + Math.sin(angle) * 120 });
    }
  });
  const label = (node) => node.kind === "hub" ? "关联组" : "记忆";
  host.innerHTML = `<svg class="akmg-canvas" viewBox="0 0 ${width} ${height}" aria-label="${options.aggregate ? "关联组概览" : "当前范围的记忆关系"}">
    <defs><marker id="akmg-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>
    <g data-graph-plane>
      ${data.edges.map((edge) => {
        const a = points.get(edge.source), b = points.get(edge.target);
        if (!a || !b) throw new Error("图关系缺少端点");
        const length = Math.hypot(b.x - a.x, b.y - a.y) || 1;
        const dx = (b.x - a.x) * 25 / length, dy = (b.y - a.y) * 25 / length;
        const active = !options.focus || !options.selected || edge.source === options.selected || edge.target === options.selected;
        return `<line x1="${a.x + dx}" y1="${a.y + dy}" x2="${b.x - dx}" y2="${b.y - dy}" class="akmg-edge ${edge.directed ? "akmg-edge-temporal" : ""}" opacity="${active ? 0.65 : 0.13}" ${edge.directed ? 'marker-end="url(#akmg-arrow)"' : ""}/>`;
      }).join("")}
      ${data.nodes.map((node, index) => {
        const p = points.get(node.id);
        const selected = node.id === options.selected;
        const text = options.aggregate ? String(node.member_count) : String(index + 1);
        return `<g transform="translate(${p.x},${p.y})" tabindex="0" role="button" data-graph-node="${escapeHtml(node.id)}" aria-label="${escapeHtml(`${label(node)}：${node.label}${node.kind === "hub" ? `，${node.member_count} 个成员` : ""}`)}" aria-pressed="${selected}" class="akmg-node ${node.kind === "hub" ? "akmg-node-hub" : ""} ${selected ? "akmg-node-selected" : ""}">
          <circle r="25" class="akmg-hit"/>
          ${node.kind === "hub" ? '<rect x="-18" y="-18" width="36" height="36" rx="8" transform="rotate(45)"/>' : '<circle r="22"/>'}
          <text text-anchor="middle" dominant-baseline="central">${text}</text>
          ${options.aggregate ? `<text class="akmg-group-label" y="40" text-anchor="middle">${escapeHtml(node.label)}</text>` : ""}
        </g>`;
      }).join("")}
    </g></svg>
    <div class="akmg-canvas-tools"><span data-graph-zoom>100%</span><button type="button" data-graph-reset>重置视图</button></div>`;
  const svg = host.querySelector("svg"), plane = host.querySelector("[data-graph-plane]");
  const pointers = new Map();
  let scale = 1, tx = 0, ty = 0, moved = false, start = null, pinch = null, pendingSelection = null;
  const update = () => {
    plane.setAttribute("transform", `translate(${tx},${ty}) scale(${scale})`);
    host.querySelector("[data-graph-zoom]").textContent = `${Math.round(scale * 100)}%`;
  };
  const local = (x, y) => new DOMPoint(x, y).matrixTransform(svg.getScreenCTM().inverse());
  const centerDistance = () => {
    const [a, b] = [...pointers.values()];
    return { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2, distance: Math.hypot(a.x - b.x, a.y - b.y) };
  };
  svg.addEventListener("pointerdown", (event) => {
    pendingSelection = null;
    pointers.set(event.pointerId, { x: event.clientX, y: event.clientY });
    svg.setPointerCapture(event.pointerId);
    if (pointers.size === 1) {
      start = { ...local(event.clientX, event.clientY), x0: event.clientX, y0: event.clientY, tx, ty };
      // DOMPoint properties are not enumerable in every WebView.
      start.x = local(event.clientX, event.clientY).x;
      start.y = local(event.clientX, event.clientY).y;
      moved = false;
    } else if (pointers.size === 2) {
      const p = centerDistance(), at = local(p.x, p.y);
      pinch = { ...p, scale, anchorX: (at.x - tx) / scale, anchorY: (at.y - ty) / scale };
      moved = true;
    }
  });
  svg.addEventListener("pointermove", (event) => {
    if (!pointers.has(event.pointerId)) return;
    pointers.set(event.pointerId, { x: event.clientX, y: event.clientY });
    if (pointers.size === 2 && pinch) {
      const p = centerDistance(), at = local(p.x, p.y);
      scale = Math.max(0.65, Math.min(2.5, pinch.scale * p.distance / Math.max(1, pinch.distance)));
      tx = at.x - pinch.anchorX * scale; ty = at.y - pinch.anchorY * scale;
      update();
    } else if (pointers.size === 1 && start && !pinch) {
      if (Math.hypot(event.clientX - start.x0, event.clientY - start.y0) > 6) moved = true;
      if (moved) {
        const at = local(event.clientX, event.clientY);
        tx = start.tx + at.x - start.x; ty = start.ty + at.y - start.y; update();
      }
    }
  });
  const finish = (event, cancelled = false) => {
    if (!pointers.has(event.pointerId)) return;
    const canSelect = !cancelled && !moved && pointers.size === 1;
    pointers.delete(event.pointerId);
    if (!pointers.size) { start = null; pinch = null; }
    if (!canSelect) return;
    const matrix = plane.getScreenCTM();
    let chosen, nearest = Infinity;
    data.nodes.forEach((node) => {
      const p = points.get(node.id), screen = new DOMPoint(p.x, p.y).matrixTransform(matrix);
      const distance = Math.hypot(screen.x - event.clientX, screen.y - event.clientY);
      const radius = Math.max(22, 25 * Math.hypot(matrix.a, matrix.b));
      if (distance <= radius && distance < nearest) { chosen = node.id; nearest = distance; }
    });
    pendingSelection = chosen || null;
  };
  svg.addEventListener("pointerup", (event) => finish(event));
  svg.addEventListener("pointercancel", (event) => finish(event, true));
  svg.addEventListener("click", (event) => {
    event.preventDefault(); event.stopPropagation();
    const id = pendingSelection; pendingSelection = null;
    if (id) options.onSelect(id);
  });
  svg.addEventListener("keydown", (event) => {
    const id = event.target.closest("[data-graph-node]")?.dataset.graphNode;
    if (id && (event.key === "Enter" || event.key === " ")) { event.preventDefault(); options.onSelect(id); }
  });
  host.querySelector("[data-graph-reset]").addEventListener("click", () => {
    scale = 1; tx = 0; ty = 0; update();
  });
}

// mobile_graph.js
function mgPager(scope, action = "page") {
  if (!scope || scope.total <= scope.page_size) return "";
  return `<nav class="akmg-pager" aria-label="分页">
    <button type="button" data-mg="${action}" data-page="${scope.page - 1}" ${scope.page === 0 ? "disabled" : ""}>上一页</button>
    <span>${scope.start + 1}–${scope.end} / ${scope.total}</span>
    <button type="button" data-mg="${action}" data-page="${scope.page + 1}" ${scope.next_page === null ? "disabled" : ""}>下一页</button></nav>`;
}

function mgNodeRows(nodes, action) {
  return `<ol class="akmg-node-list">${nodes.map((node, index) => `<li>
    <button type="button" data-mg="${action}" data-node="${escapeHtml(node.id)}">
      <span class="akmg-node-number ${node.kind === "hub" ? "akmg-node-number-hub" : ""}">${index + 1}</span>
      <span><strong>${escapeHtml(node.label)}</strong><small>${escapeHtml(shortTime(node.ts))} · ${node.kind === "hub"
        ? `${node.member_count} 段记忆 · ${node.shared_count} 段共享`
        : node.group_count > 1 ? `共享成员 · 属于 ${node.group_count} 个关联组` : `${node.group_count} 个关联组`}</small></span>
      <span aria-hidden="true">›</span>
    </button></li>`).join("")}</ol>`;
}

function mountMemoryGraph(host, context) {
  if (!context.capabilities?.queryTransports?.includes("https")) {
    host.innerHTML = '<p class="akasha-mobile-error">当前客户端不支持记忆图的数据通道，请更新客户端后查看。</p>';
    return undefined;
  }
  let active = true, serial = 0, busy = false, data = null, overview = null;
  let route = { method: "graph.overview", params: {} }, selected = null, focus = true;
  let queryText = "", sourceOpen = false, notice = "", failure = null;
  const trail = [];

  const request = async (method, params) => {
    const result = await context.query(method, params, { cache: "none", transport: "https" });
    if (result.schema !== "akasha.memory-graph.v1" || !["ready", "empty", "stale", "unavailable", "disabled", "not_found"].includes(result.status)) {
      throw new Error("记忆图响应格式不受支持");
    }
    if (result.status === "ready" && !/^[0-9a-f]{64}$/.test(result.revision)) throw new Error("记忆图版本缺失");
    if (result.status === "ready" && params.revision && result.revision !== params.revision) throw new Error("记忆图版本不一致，请刷新");
    return result;
  };
  const save = () => ({ route, data, selected, sourceOpen, scroll: host.getBoundingClientRect().top });
  const go = async (method, params = {}, { remember = true } = {}) => {
    if (!active) return;
    if (remember && data && !failure) { trail.push(save()); if (trail.length > 32) trail.shift(); }
    route = { method, params }; selected = null; sourceOpen = false; notice = "";
    const token = ++serial;
    busy = true; failure = null; render();
    try {
      const value = await request(method, params);
      if (!active || token !== serial) return;
      if (!["ready", "empty"].includes(value.status)) { failure = value; busy = false; render(); return; }
      data = value; selected = value.root_id || null;
      if (method === "graph.overview") overview = value;
      busy = false; render();
    } catch (error) {
      if (!active || token !== serial) return;
      busy = false; failure = { status: "error", message: error.message || "读取失败，请重试" }; render();
    }
  };
  const back = () => {
    ++serial; busy = false; failure = null; notice = "";
    const previous = trail.pop();
    if (!previous) { go("graph.overview", {}, { remember: false }); return; }
    ({ route, data, selected, sourceOpen } = previous); render();
    host.scrollIntoView({ block: "start" });
  };
  const revision = () => data?.revision || overview?.revision;
  const navigate = (method, nodeId, more = {}) => go(method, { revision: revision(), node_id: nodeId, ...more });
  const refresh = async () => {
    const previous = route, token = ++serial;
    busy = true; failure = null; notice = ""; render();
    try {
      const fresh = await request("graph.overview", {});
      if (!active || token !== serial) return;
      trail.length = 0; overview = fresh; data = fresh;
      if (fresh.status !== "ready") {
        route = { method: "graph.overview", params: {} }; busy = false;
        failure = fresh.status === "empty" ? null : fresh; render(); return;
      }
      const next = previous.method === "graph.overview" || previous.method === "graph.group"
        ? { method: "graph.overview", params: {} }
        : { method: previous.method, params: { ...previous.params, revision: fresh.revision, page: 0 } };
      go(next.method, next.params, { remember: false });
    } catch (error) {
      if (!active || token !== serial) return;
      busy = false; failure = { status: "error", message: error.message }; render();
    }
  };
  const loadSource = async (field) => {
    const prior = data.sources[field];
    if (prior.next_offset === null || busy) return;
    const token = ++serial; busy = true;
    try {
      const value = await request("graph.source", { revision: revision(), node_id: data.node.id, field, offset: prior.next_offset });
      if (!active || token !== serial) return;
      if (value.status !== "ready") { failure = value; busy = false; render(); return; }
      const part = value.source;
      if (part.field !== field || part.offset !== prior.next_offset || part.total_chars !== prior.total_chars) throw new Error("原文分段不连续，请刷新");
      data.sources[field] = { ...part, offset: 0, text: prior.text + part.text };
      busy = false; render();
    } catch (error) {
      if (!active || token !== serial) return;
      busy = false; notice = error.message; render();
    }
  };
  const copySource = async () => {
    try {
      const text = `你\n${data.sources.user.text}\n\nRoxy\n${data.sources.assistant.text}`;
      await navigator.clipboard.writeText(text);
      if (active) { notice = "已复制完整原文"; render(); }
    } catch { if (active) { notice = "复制未完成，可长按原文选择复制"; render(); } }
  };

  function summary() {
    if (!overview?.totals) return "";
    return `<div class="akmg-summary"><div><strong>${overview.totals.turns}</strong><span>段记忆（已去重）</span></div>
      <div><strong>${overview.totals.groups}</strong><span>个关联组</span></div></div>
      <p class="akmg-caption">最近纳入：${escapeHtml(shortTime(overview.included_through?.ts))} · 发布 ${escapeHtml(overview.revision.substring(0, 8))}</p>`;
  }
  function sources() {
    if (data.node.kind === "hub") return '<p class="akmg-explanation">关联组由记忆关系形成，没有独立原文或自动生成的主题。</p>';
    const complete = Object.values(data.sources).every((item) => item.next_offset === null);
    return `<section class="akmg-sources"><button type="button" data-mg="source-toggle" aria-expanded="${sourceOpen}">${sourceOpen ? "收起原文" : "展开原文"}</button>
      ${sourceOpen ? Object.entries(data.sources).map(([field, item]) => `<article><h3>${field === "user" ? "原始输入" : "原始回复"}</h3>
        <div class="akmg-source-text">${escapeHtml(item.text || "（空正文）")}</div>
        <p class="akmg-caption">已显示 ${[...item.text].length} / ${item.total_chars} 字符</p>
        ${item.next_offset !== null ? `<button type="button" data-mg="source-more" data-field="${field}">继续阅读${field === "user" ? "输入" : "回复"}</button>` : ""}</article>`).join("") : ""}
      ${sourceOpen ? `<button type="button" data-mg="copy" ${complete ? "" : "disabled"}>${complete ? "复制完整原文" : "读完原文后可复制全文"}</button>` : ""}</section>`;
  }
  function detailBody() {
    const node = data.node, related = data.related.nodes.filter((item) => item.id !== node.id);
    return `<header class="akmg-detail-header"><span class="akmg-kind">${node.kind === "hub" ? "关联组" : "回合记忆"}</span>
      <h2>${escapeHtml(node.label)}</h2><p>${escapeHtml(shortTime(node.ts))}</p></header>
      ${node.group_count > 1 ? `<p class="akmg-shared">共享成员：同一段记忆属于 ${node.group_count} 个关联组。</p>` : ""}
      ${sources()}<section><h3>${node.kind === "hub" ? "组内成员" : "所属关联组"}</h3>
      ${mgPager(data.related.scope)}${mgNodeRows(related, "local")}
      ${related.length ? "" : '<p class="akmg-caption">暂无成员关系。</p>'}</section>
      <button class="akmg-primary" type="button" data-mg="local" data-node="${escapeHtml(node.id)}">在局部图中定位</button>`;
  }
  function overviewBody() {
    const group = route.method === "graph.group";
    return `${summary()}<form class="akmg-search" data-mg-search><label class="akmg-sr-only" for="akmg-search">搜索全部已发布记忆</label>
      <input id="akmg-search" type="search" maxlength="200" placeholder="搜索全部已发布记忆" value="${escapeHtml(queryText)}"><button type="submit">搜索</button></form>
      <div class="akmg-section-title"><h3>${group ? "组内记忆" : "关联组概览"}</h3>
      ${group ? '<button type="button" data-mg="collapse">收起关联组</button>' : ""}</div>
      <p class="akmg-caption">${group ? `当前显示 ${data.scope.end - data.scope.start} / ${data.scope.total} 个成员` : "点击关联组展开。成员可以共享，组内计数不可相加。"}</p>
      ${mgPager(data.scope)}<div data-mg-canvas></div>
      ${mgNodeRows(group ? data.nodes.filter((n) => n.id !== data.root_id) : data.nodes, group ? "local" : "group")}
      ${data.nodes.length ? "" : '<p class="akmg-caption">尚无关联组，可从最近记忆或搜索开始。</p>'}
      ${!group && overview.recent?.length ? `<h3>最近记忆</h3>${mgNodeRows(overview.recent, "local")}` : ""}`;
  }
  function localBody() {
    const node = data.nodes.find((item) => item.id === selected) || data.nodes[0];
    const incident = data.edges.filter((edge) => edge.source === node.id || edge.target === node.id);
    return `<h2>局部记忆图</h2><p class="akmg-caption">一跳邻居：当前 ${data.scope.end - data.scope.start} / ${data.scope.total} 个 · 发布 ${escapeHtml(data.revision.substring(0, 8))}</p>
      <div class="akmg-filters" aria-label="关联类型">${[["all", "全部"], ["membership", "成员关系"], ["temporal", "时间关系"]].map(([key, name]) => `<button type="button" data-mg="filter" data-filter="${key}" aria-pressed="${data.filter === key}">${name}</button>`).join("")}</div>
      <label class="akmg-focus"><input type="checkbox" data-mg-focus ${focus ? "checked" : ""}>聚焦所选记忆的连线</label>
      ${mgPager(data.scope)}<div data-mg-canvas></div>
      <p class="akmg-caption">圆形为记忆，菱形为关联组；虚线箭头表示有方向的时间关系。</p>
      <section class="akmg-selection"><strong>${escapeHtml(node.label)}</strong>
        ${node.group_count > 1 ? `<p class="akmg-shared">共享成员 · ${node.group_count} 个关联组</p>` : ""}
        <div class="akmg-selection-actions"><button class="akmg-primary" type="button" data-mg="detail" data-node="${escapeHtml(node.id)}">查看详情</button>
        <button type="button" data-mg="local" data-node="${escapeHtml(node.id)}">以此为中心</button></div></section>
      <details class="akmg-relations"><summary>所选节点在当前范围内的 ${incident.length} 条关系</summary><ul>${incident.map((edge) => {
        const from = data.nodes.find((n) => n.id === edge.source), to = data.nodes.find((n) => n.id === edge.target);
        return `<li>${escapeHtml(from.label)} ${edge.directed ? "→" : "↔"} ${escapeHtml(to.label)}<small>${edge.kind === "membership" ? "成员关系" : "时间关系"} · 关联强度 ${Number(edge.strength).toPrecision(3)}</small></li>`;
      }).join("")}</ul></details>
      ${mgNodeRows(data.nodes, "select")}`;
  }
  function render() {
    if (!active) return;
    const isOverview = ["graph.overview", "graph.group"].includes(route.method);
    let body;
    if (busy && !sourceOpen) body = '<p class="akmg-state" role="status">正在读取已发布记忆…</p>';
    else if (failure) body = `<section class="akmg-state" role="alert"><h2>${({ stale: "记忆图已更新", unavailable: "记忆数据暂不可用", disabled: "Akasha 尚未启用", not_found: "记忆已不在当前图中" })[failure.status] || "读取失败"}</h2>
      <p>${escapeHtml(failure.message || "请稍后重试")}</p><button type="button" data-mg="refresh">刷新记忆图</button><button type="button" data-mg="home">返回概览</button></section>`;
    else if (!data || data.status === "empty") body = '<section class="akmg-state"><h2>记忆图还是空的</h2><p>完成对话并发布记忆后，可在这里查看。</p></section>';
    else if (route.method === "graph.detail") body = detailBody();
    else if (route.method === "graph.search") body = `<h2>搜索结果</h2><p class="akmg-caption">“${escapeHtml(queryText)}” · 全部已发布记忆中共 ${data.scope.total} 条</p>${mgPager(data.scope)}${mgNodeRows(data.items, "local")}${data.items.length ? "" : '<p class="akmg-state">没有找到匹配的记忆。</p>'}`;
    else body = isOverview ? overviewBody() : localBody();
    host.innerHTML = `<div class="akmg"><header class="akmg-top"><button type="button" data-mg="back" ${trail.length ? "" : "disabled"}>返回</button><strong>Akasha 记忆图</strong><button type="button" data-mg="refresh">刷新</button></header>
      ${notice ? `<p class="akmg-notice" role="status">${escapeHtml(notice)}</p>` : ""}${body}
      <p class="akmg-footnote">只读浏览 · 关联强度不代表事实可信度或因果关系</p></div>`;
    const canvas = host.querySelector("[data-mg-canvas]");
    if (canvas && data) drawMemoryGraph(canvas, data, {
      aggregate: route.method === "graph.overview", selected, focus,
      onSelect: (id) => {
        if (route.method === "graph.overview") navigate("graph.group", id);
        else if (route.method === "graph.group" && id !== data.root_id) navigate("graph.neighbors", id);
        else { selected = id; render(); }
      },
    });
    host.querySelector("[data-mg-search]")?.addEventListener("submit", (event) => {
      event.preventDefault(); queryText = host.querySelector("input[type=search]").value.trim();
      if (queryText) go("graph.search", { revision: revision(), query: queryText });
    });
    host.querySelector("[data-mg-focus]")?.addEventListener("change", (event) => { focus = event.target.checked; render(); });
    host.querySelectorAll("[data-mg]").forEach((button) => button.addEventListener("click", () => {
      const action = button.dataset.mg, id = button.dataset.node;
      if (action === "back") back();
      else if (action === "refresh") refresh();
      else if (action === "home") { trail.length = 0; go("graph.overview", {}, { remember: false }); }
      else if (action === "collapse") back();
      else if (action === "group") navigate("graph.group", id);
      else if (action === "local") navigate("graph.neighbors", id);
      else if (action === "detail") navigate("graph.detail", id);
      else if (action === "select") { selected = id; render(); }
      else if (action === "filter") go("graph.neighbors", { ...route.params, filter: button.dataset.filter, page: 0 }, { remember: false });
      else if (action === "page") go(route.method, { ...route.params, page: Number(button.dataset.page) }, { remember: false });
      else if (action === "source-toggle") { sourceOpen = !sourceOpen; render(); }
      else if (action === "source-more") loadSource(button.dataset.field);
      else if (action === "copy") copySource();
    }));
  }
  go("graph.overview", {}, { remember: false });
  return () => { active = false; ++serial; trail.length = 0; data = null; overview = null; host.replaceChildren(); };
}

// mobile_ui_entry.js
function mountAkasha(host, context) {
  host.innerHTML = `<section class="akasha-mobile-root">
    <nav class="akmg-tabs" aria-label="Akasha 页面">
      <button type="button" data-akasha-tab="graph" aria-pressed="true">记忆图</button>
      <button type="button" data-akasha-tab="inspector" aria-pressed="false">Inspector</button>
    </nav><div data-akasha-content></div></section>`;
  const content = host.querySelector("[data-akasha-content]");
  let cleanup;
  const select = (name) => {
    cleanup?.();
    host.querySelectorAll("[data-akasha-tab]").forEach((button) => {
      button.setAttribute("aria-pressed", String(button.dataset.akashaTab === name));
    });
    cleanup = name === "graph" ? mountMemoryGraph(content, context) : mountInspector(content, context);
  };
  host.querySelectorAll("[data-akasha-tab]").forEach((button) => {
    button.addEventListener("click", () => select(button.dataset.akashaTab));
  });
  select("graph");
  return () => { cleanup?.(); host.replaceChildren(); };
}

export default {
  slots: { "turn.before_reasoning": { mount: mountRecall } },
  dashboard: { mount: mountAkasha },
};
