"""Assemble the import-free mobile asset served by the host's blob loader."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src" / "akasha"
SOURCES = ("mobile_inspector.js", "mobile_graph_canvas.js", "mobile_graph.js", "mobile_ui_entry.js")

if __name__ == "__main__":
    content = "// Generated by scripts/build_mobile_ui.py; edit the named source modules.\n"
    content += "\n".join(f"// {name}\n" + (ROOT / name).read_text() for name in SOURCES)
    (ROOT / "mobile_ui.js").write_text(content)
